package com.prince.ai.ragfusion.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SearchResponse {

  /**
   * Final answer generated by Claude
   */
  private String answer;

  /**
   * Final retrieved chunks after RRF
   */
  private List<Chunk> retrievedChunks;

  /**
   * Pure Vector Search results
   */
  private List<SearchResult> vectorResults;

  /**
   * Pure BM25 Search results
   */
  private List<SearchResult> bm25Results;

}